### ISSUE TITLE
Server would not launch 

### ISSUE THREAD

**Issue by damdoomy** [diogo-webber/vox-launcher#23]
It's my first time using this launcher and it keeps saying "Before using Vox for the first time, launch this cluster from the in-game menu then click try again" which is what I exactly did yet it makes no difference. I made sure to follow step by step with the guides on youtube, tried different clusters, tried from a friend's computer, and still wouldn't launch. 

I'm not too sure what could be happening with it but let me know if I need to provide any more information. 
Thanks a lot in advance <3

**Comment by damdoomy** [comment]
Nevermind, resolved it! turns out my computer messed up the file order hehe ^.^

**Comment by diogo-webber** [comment]
Hi damdoomy, glad you could figure this out! Could you share more about it, since it might help other users with similar issues? Thank you.
