### ISSUE TITLE
Server created does not have dedicated server icon

### ISSUE THREAD

**Issue by sayaneko514** [diogo-webber/vox-launcher#6]
Everything loads up quite smoothly. However, when I launch the server, it doesn't have the dedicated server icon, nor is 'Dedicated Server' being toggled in the server details.
![image](https://github.com/diogo-webber/vox-launcher/assets/59753147/1fe3c383-4792-4d7c-8dfb-386828d0b147)
![image](https://github.com/diogo-webber/vox-launcher/assets/59753147/e4084e50-f365-413e-8349-69c42b52a278)

**Comment by Dian-E2B** [comment]
same.  it's like hosted but you can disconnect....

**Comment by July6289** [comment]
yup, this happened to me too

**Comment by diogo-webber** [comment]
Hi Rui Tang, thanks for reporting.

Just letting you know that I'm aware of the issue.
However, I don't have time at the moment to take a look at it.

Thank you for the patience.

**Comment by diogo-webber** [comment]
This has been fixed.

**Comment by diogo-webber** [comment]
This has been fixed.
