### ISSUE TITLE
Virus detected on download

### ISSUE THREAD

**Issue by KainMorgen** [diogo-webber/vox-launcher#9]
Chrome automatically deletes the archive on download, as it detects a virus hidden inside.
Screenshot in German:
![83v8GlC](https://github.com/diogo-webber/vox-launcher/assets/12435714/aeea581e-64da-432f-91ff-135a0ea37e8b)

**Comment by diogo-webber** [comment]
Hi Kain, thanks for reporting.

I've just added a section to the README explaining why that is happening.

From `README.md`:

**Windows Defender is flagging Vox Launcher as a threat, why is this happening?**
> The tool called [Pyinstaller](https://github.com/pyinstaller/pyinstaller), which is used to bundle the app into an executable, is also used by people who actually make malicious software. Windows Defender recognizes some similar patterns in the executable and includes Vox Launcher as a threat.

> Usually creating a new version solves this temporarily, but there's not much to be done in the long term other than rebuilding the whole app in another programming language, which I don't have the time or desire to do at the moment. The only thing you could do is to [add an exclusion to Windows Defender](https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26).
